apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: nginx-deployment-aws-secrets
spec:
  parameters:
    objects: |
      - objectName: "MySecret"
        objectType: "secretsmanager"
  provider: aws
  secretObjects:
  - data:
    - key: things
      objectName: ACSPSecrets
    secretName: ACSPEKSSecret
    type: Opaque
