apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: nginx-deployment-aws-secrets
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "MySecret"
        objectType: "secretsmanager"
        jmesPath:
          - path: password
            objectAlias: secretPassword
          - path: accessKey
            objectAlias: secretAccessKey
          - path: version
            objectAlias: secretVersion
  secretObjects:
    - secretName: my-aws-secret
      type: Opaque
      data:
        - objectName: secretPassword
          key: secret_password
        - objectName: secretAccessKey
          key: secret_access_key
        - objectName: secretVersion
          key: secret_version
